---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-splunk-enterprise
  failurePolicy: Fail
  name: vsplunk.kb.io
  rules:
  - apiGroups:
    - enterprise.splunk.com
    apiVersions:
    - v4
    operations:
    - CREATE
    - UPDATE
    resources:
    - standalones
    - indexerclusters
    - searchheadclusters
    - clustermanagers
    - licensemanagers
    - monitoringconsoles
  sideEffects: None
