# permissions for end users to edit kvservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: kvservice-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: splunk-operator
    app.kubernetes.io/part-of: splunk-operator
    app.kubernetes.io/managed-by: kustomize
  name: kvservice-editor-role
rules:
- apiGroups:
  - enterprise.splunk.com
  resources:
  - kvservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - enterprise.splunk.com
  resources:
  - kvservices/status
  verbs:
  - get
