---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    k8s-app: splunk-kubecontroller
  name: splunkenterprises.enterprise.splunk.com
spec:
  group: enterprise.splunk.com
  names:
    kind: SplunkEnterprise
    listKind: SplunkEnterpriseList
    plural: splunkenterprises
    shortNames:
      - enterprise
    singular: splunkenterprise
  scope: Namespaced
  version: v1alpha1
