apiVersion: enterprise.splunk.com/v1alpha1
kind: SplunkEnterprise
metadata:
  name: example-splunkenterprise
spec:
  config:
    splunkPassword: helloworld456
    splunkStartArgs: --accept-license
    enableDFS: true
    splunkLicense:
      volumeSource:
        configMap:
          name: splunk-enterprise.lic
      licensePath: /splunk-enterprise.lic
  topology:
    indexers: 3
    searchHeads: 3
    sparkWorkers: 3