apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: splunkenterprises.enterprise.splunk.com
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.status.searchPhase
    description: Status of search head cluster
    name: Search
    type: integer
  - JSONPath: .spec.status.indexingPhase
    description: Status of indexer cluster
    name: Indexing
    type: integer
  - JSONPath: .spec.topology.dfsPhase
    description: Status of DFS spark workers
    name: DFS
    type: integer
  - JSONPath: .spec.topology.standalonePhase
    description: Status of standlone instances
    name: Standalone
    type: integer
  - JSONPath: .status.licenseMasterPhase
    description: Status of license master
    name: LM
    type: string
  - JSONPath: .status.clusterMasterPhase
    description: Status of cluster master
    name: CM
    type: string
  - JSONPath: .status.deployerPhase
    description: Status of deployer
    name: Dep
    type: string
  group: enterprise.splunk.com
  names:
    kind: SplunkEnterprise
    listKind: SplunkEnterpriseList
    plural: splunkenterprises
    shortNames:
    - enterprise
    - se
    singular: splunkenterprise
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha2
  versions:
  - name: v1alpha2
    served: true
    storage: true
  - name: v1alpha1
    served: true
    storage: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: splunk:operator:namespace-manager
rules:
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  - persistentvolumeclaims
  - configmaps
  - secrets
  - pods
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - enterprise.splunk.com
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
  name: splunk:operator:resource-manager
rules:
  - apiGroups:
      - enterprise.splunk.com
    resources:
      - '*'
    verbs:
      - '*'
---
apiVersion: v1
kind: Namespace
metadata:
  name: splunk-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: splunk-operator
  namespace: splunk-operator
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: splunk:operator:resource-manager
subjects:
- kind: ServiceAccount
  name: splunk-operator
  namespace: splunk-operator
roleRef:
  kind: ClusterRole
  name: splunk:operator:resource-manager
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: splunk:operator:namespace-manager
  namespace: splunk-operator
subjects:
- kind: ServiceAccount
  name: splunk-operator
  namespace: splunk-operator
roleRef:
  kind: ClusterRole
  name: splunk:operator:namespace-manager
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: splunk-operator
  namespace: splunk-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: splunk-operator
  template:
    metadata:
      labels:
        name: splunk-operator
    spec:
      serviceAccountName: splunk-operator
      containers:
        - name: splunk-operator
          image: splunk/splunk-operator
          imagePullPolicy: IfNotPresent
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "splunk-operator"
            - name: SPLUNK_IMAGE
              value: "splunk/splunk:8.0"
            - name: SPARK_IMAGE
              value: "splunk/spark"
