apiVersion: apps/v1
kind: Deployment
metadata:
  name: splunk-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: splunk-operator
  template:
    metadata:
      labels:
        name: splunk-operator
    spec:
      serviceAccountName: splunk-operator
      containers:
        - name: splunk-operator
          # Replace this with the built image name
          image: cloudrepo-docker-playground.jfrog.io/pcp/splunk-operator
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - splunk-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "splunk-operator"
            - name: SPLUNK_IMAGE
              value: "splunk/splunk"
            - name: SPLUNK_DFS_IMAGE
              value: "cloudrepo-docker-playground.jfrog.io/dfs/splunk-dfs"
            - name: SPLUNK_SPARK_IMAGE
              value: "cloudrepo-docker-playground.jfrog.io/dfs/splunk-spark"
            - name: IMAGE_PULL_POLICY
              value: "Always"
