---
# The following patch adds a directive for certmanager to inject CA into the CRD
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: standalones.enterprise.splunk.com
spec:
  preserveUnknownFields: false

---    
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clustermasters.enterprise.splunk.com
spec:
  preserveUnknownFields: false

---    
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: licensemasters.enterprise.splunk.com
spec:
  preserveUnknownFields: false

---    
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: licensemanagers.enterprise.splunk.com
spec:
  preserveUnknownFields: false

---    
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: indexerclusters.enterprise.splunk.com
spec:
  preserveUnknownFields: false

---    
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: monitoringconsoles.enterprise.splunk.com
spec:
  preserveUnknownFields: false

---    
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: searchheadclusters.enterprise.splunk.com
spec:
  preserveUnknownFields: false