apiVersion: enterprise.splunk.com/v4
kind: MonitoringConsole
metadata:
  name: monitoringconsole-sample
  namespace: splunk-operator
  finalizers:
    - enterprise.splunk.com/delete-pvc
spec:
  # Add fields here
