apiVersion: enterprise.splunk.com/v4
kind: IndexerCluster
metadata:
  name: indexercluster-sample
  namespace: splunk-operator
  finalizers:
    - enterprise.splunk.com/delete-pvc
spec:
  clusterManagerRef:
    name: clustermanager-sample
  # Add fields here
