apiVersion: enterprise.splunk.com/v4
kind: ClusterManager
metadata:
  name: clustermanager-sample
  namespace: splunk-operator
  finalizers:
    - enterprise.splunk.com/delete-pvc
spec:
  # Add fields here
