## Append samples you want in your CSV to this file as resources ##
resources:
- enterprise_v3_clustermaster.yaml
- enterprise_v3_indexercluster.yaml
- enterprise_v3_licensemaster.yaml
- enterprise_v3_monitoringconsole.yaml
- enterprise_v3_searchheadcluster.yaml
- enterprise_v3_standalone.yaml
- enterprise_v4_clustermanager.yaml
- enterprise_v4_licensemanager.yaml
- enterprise_v4_monitoringconsole.yaml
- enterprise_v4_indexercluster.yaml
- enterprise_v4_searchheadcluster.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
