apiVersion: splunk.com/v4
kind: KVService
metadata:
  labels:
    app.kubernetes.io/name: splunk-operator
    app.kubernetes.io/managed-by: kustomize
  name: kvservice-sample
spec:
  # TODO(user): Add fields here
