apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [{
        "apiVersion": "enterprise.splunk.com/v1",
        "kind": "IndexerCluster",
        "metadata": {
          "name": "example",
          "finalizers": [ "enterprise.splunk.com/delete-pvc" ]
        },
        "spec": {
          "replicas": 1
        }
      },
      {
        "apiVersion": "enterprise.splunk.com/v1",
        "kind": "LicenseMaster",
        "metadata": {
          "name": "example",
          "finalizers": [ "enterprise.splunk.com/delete-pvc" ]
        },
        "spec": {}
      },
      {
        "apiVersion": "enterprise.splunk.com/v1",
        "kind": "SearchHeadCluster",
        "metadata": {
          "name": "example",
          "finalizers": [ "enterprise.splunk.com/delete-pvc" ]
        },
        "spec": {
          "replicas": 1
        }
      },
      {
        "apiVersion": "enterprise.splunk.com/v1",
        "kind": "Standalone",
        "metadata": {
          "name": "example",
          "finalizers": [ "enterprise.splunk.com/delete-pvc" ]
        },
        "spec": {}
      }]
    capabilities: Basic Install
  name: splunk.v1.0.0-RC
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: ClusterMaster is the Schema for the clustermasters API
      kind: ClusterMaster
      name: clustermasters.enterprise.splunk.com
      version: v1
      resources:
      - kind: StatefulSets
        version: apps/v1
      - kind: Deployments
        version: apps/v1
      - kind: Pods
        version: v1
      - kind: Services
        version: v1
      - kind: ConfigMaps
        version: v1
      - kind: Secrets
        version: v1
      displayName: IndexerCluster
    - description: IndexerCluster is the Schema for a Splunk Enterprise indexer cluster
      kind: IndexerCluster
      name: indexerclusters.enterprise.splunk.com
      version: v1
      resources:
      - kind: StatefulSets
        version: apps/v1
      - kind: Deployments
        version: apps/v1
      - kind: Pods
        version: v1
      - kind: Services
        version: v1
      - kind: ConfigMaps
        version: v1
      - kind: Secrets
        version: v1
      displayName: LicenseMaster
    - description: LicenseMaster is the Schema for a Splunk Enterprise license master.
      kind: LicenseMaster
      name: licensemasters.enterprise.splunk.com
      version: v1
      resources:
      - kind: StatefulSets
        version: apps/v1
      - kind: Deployments
        version: apps/v1
      - kind: Pods
        version: v1
      - kind: Services
        version: v1
      - kind: ConfigMaps
        version: v1
      - kind: Secrets
        version: v1
      displayName: SearchHeadCluster
    - description: SearchHeadCluster is the Schema for a Splunk Enterprise search
        head cluster
      kind: SearchHeadCluster
      name: searchheadclusters.enterprise.splunk.com
      version: v1
      resources:
      - kind: StatefulSets
        version: apps/v1
      - kind: Deployments
        version: apps/v1
      - kind: Pods
        version: v1
      - kind: Services
        version: v1
      - kind: ConfigMaps
        version: v1
      - kind: Secrets
        version: v1
    - description: Standalone is the Schema for a Splunk Enterprise standalone instances.
      kind: Standalone
      name: standalones.enterprise.splunk.com
      version: v1
      resources:
      - kind: StatefulSets
        version: apps/v1
      - kind: Deployments
        version: apps/v1
      - kind: Pods
        version: v1
      - kind: Services
        version: v1
      - kind: ConfigMaps
        version: v1
      - kind: Secrets
        version: v1
      displayName: Standalone
  description: Placeholder description
  displayName: Splunk
  install:
    spec:
      deployments:
      - name: splunk-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: splunk-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: splunk-operator
            spec:
              containers:
              - env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: splunk-operator
                - name: RELATED_IMAGE_SPLUNK_ENTERPRISE
                  value: docker.io/splunk/splunk:8.1.3
                image: docker.io/splunk/splunk-operator:1.0.0-RC
                imagePullPolicy: IfNotPresent
                name: splunk-operator
                resources: {}
              serviceAccountName: splunk-operator
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - services
          - endpoints
          - persistentvolumeclaims
          - configmaps
          - secrets
          - pods
          - pods/exec
          - serviceaccounts
          verbs:
          - create
          - delete
          - deletecollection
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - create
          - delete
          - deletecollection
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - enterprise.splunk.com
          resources:
          - '*'
          verbs:
          - '*'
        serviceAccountName: splunk-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  maturity: alpha
  provider: {}
  replaces: splunk.v0.0.0
  version: 1.0.0-RC
