---
{{- if .Values.clusterScope }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "splunk-operator.serviceAccountName" . }}-rm
  labels:
    {{- include "splunk-operator.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name:  {{ include "splunk-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "splunk-operator.serviceAccountName" . }}-rm
  apiGroup: rbac.authorization.k8s.io
{{- end }}