title: Splunk Operator for Kubernetes
#email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  The Splunk Operator for Kubernetes (SOK) makes it easy for Splunk Administrators to deploy and operate Enterprise deployments in a Kubernetes infrastructure. 
  
  Packaged as a container, it uses the operator pattern to manage Splunk-specific custom resources, following best practices to manage all the underlying Kubernetes objects for you.
github_username:  mcinnesd
domain: mcinnesd.github.io 
url: "https://mcinnesd.github.io" # the base hostname & protocol for your site, e.g. http://example.com

favicon_ico: /assets/images/favicon.ico

aux_links:
  "Splunk Operator for Kubernetes on GitHub":
    - "//github.com/mcinnesd/splunk-operator"


# Build settings
theme: just-the-docs
# plugins:
#   - jekyll-feed

collections:
  helm:
    permalink: "/:path/"
    output: true


# The colors grey-lt, grey-dk, purple,
# blue, green, yellow, and red are predefined
callouts:
  warning:
    title: Warning
    color: yellow
  note:
    title: Note
    color: blue
  highlight:
    color: yellow
  important:
    title: Important
    color: red


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
