title: Splunk Operator for Kubernetes
url: https://splunk.github.io/splunk-operator
baseurl: "/splunk-operator"
description: Documentation for deploying and operating Splunk Enterprise with the Splunk Operator for Kubernetes.
remote_theme: just-the-docs/just-the-docs
search_enabled: true
plugins:
  - jekyll-remote-theme
aux_links:
  "View on GitHub":
    - https://github.com/splunk/splunk-operator
aux_links_new_tab: true
footer_content: "Copyright &copy; Splunk, a Cisco company."
markdown: kramdown
kramdown:
  input: GFM
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
