---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.16.1
  name: buses.enterprise.splunk.com
spec:
  group: enterprise.splunk.com
  names:
    kind: Bus
    listKind: BusList
    plural: buses
    shortNames:
    - bus
    singular: bus
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Status of bus
      jsonPath: .status.phase
      name: Phase
      type: string
    - description: Age of bus resource
      jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    - description: Auxillary message describing CR status
      jsonPath: .status.message
      name: Message
      type: string
    name: v4
    schema:
      openAPIV3Schema:
        description: Bus is the Schema for the buses API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: BusSpec defines the desired state of Bus
            properties:
              provider:
                description: Provider of queue resources
                enum:
                - sqs
                type: string
              sqs:
                description: sqs specific inputs
                properties:
                  dlq:
                    description: Name of the dead letter queue resource
                    minLength: 1
                    type: string
                  endpoint:
                    description: Amazon SQS Service endpoint
                    pattern: ^https://sqs(?:-fips)?\.[a-z]+-[a-z]+(?:-[a-z]+)?-\d+\.amazonaws\.com(?:\.cn)?(?:/[A-Za-z0-9._-]+(?:/[A-Za-z0-9._-]+)*)?$
                    type: string
                  name:
                    description: Name of the queue
                    minLength: 1
                    type: string
                  region:
                    description: Region of the resources
                    pattern: ^(?:us|ap|eu|me|af|sa|ca|cn|il)(?:-[a-z]+){1,3}-\d$
                    type: string
                required:
                - dlq
                - name
                - region
                type: object
            required:
            - provider
            type: object
            x-kubernetes-validations:
            - message: sqs must be provided when provider is sqs
              rule: self.provider != 'sqs' || has(self.sqs)
          status:
            description: BusStatus defines the observed state of Bus
            properties:
              message:
                description: Auxillary message describing CR status
                type: string
              phase:
                description: Phase of the bus
                enum:
                - Pending
                - Ready
                - Updating
                - ScalingUp
                - ScalingDown
                - Terminating
                - Error
                type: string
              resourceRevMap:
                additionalProperties:
                  type: string
                description: Resource revision tracker
                type: object
            type: object
        type: object
    served: true
    storage: true
    subresources:
      scale:
        labelSelectorPath: .status.selector
        specReplicasPath: .spec.replicas
        statusReplicasPath: .status.replicas
      status: {}
