---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.16.1
  name: largemessagestores.enterprise.splunk.com
spec:
  group: enterprise.splunk.com
  names:
    kind: LargeMessageStore
    listKind: LargeMessageStoreList
    plural: largemessagestores
    shortNames:
    - lms
    singular: largemessagestore
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Status of large message store
      jsonPath: .status.phase
      name: Phase
      type: string
    - description: Age of large message store resource
      jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    - description: Auxillary message describing CR status
      jsonPath: .status.message
      name: Message
      type: string
    name: v4
    schema:
      openAPIV3Schema:
        description: LargeMessageStore is the Schema for the largemessagestores API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: LargeMessageStoreSpec defines the desired state of LargeMessageStore
            properties:
              provider:
                description: Provider of queue resources
                enum:
                - s3
                type: string
              s3:
                description: s3 specific inputs
                properties:
                  endpoint:
                    description: S3-compatible Service endpoint
                    pattern: ^https://s3(?:-fips)?\.[a-z]+-[a-z]+(?:-[a-z]+)?-\d+\.amazonaws\.com(?:\.cn)?(?:/[A-Za-z0-9._-]+(?:/[A-Za-z0-9._-]+)*)?$
                    type: string
                  path:
                    description: S3 bucket path
                    pattern: ^s3://[a-z0-9.-]{3,63}(?:/[^\s]+)?$
                    type: string
                required:
                - path
                type: object
            required:
            - provider
            - s3
            type: object
            x-kubernetes-validations:
            - message: s3 must be provided when provider is s3
              rule: self.provider != 's3' || has(self.s3)
          status:
            description: LargeMessageStoreStatus defines the observed state of LargeMessageStore.
            properties:
              message:
                description: Auxillary message describing CR status
                type: string
              phase:
                description: Phase of the large message store
                enum:
                - Pending
                - Ready
                - Updating
                - ScalingUp
                - ScalingDown
                - Terminating
                - Error
                type: string
              resourceRevMap:
                additionalProperties:
                  type: string
                description: Resource revision tracker
                type: object
            type: object
        type: object
    served: true
    storage: true
    subresources:
      scale:
        labelSelectorPath: .status.selector
        specReplicasPath: .spec.replicas
        statusReplicasPath: .status.replicas
      status: {}
