name: Bias Language
permissions:
  contents: read
  packages: write
  pull-requests: write
on: [push]
jobs:
  biased_lang:
    runs-on: ubuntu-latest
    name: Detecting Biased Language
    steps:
      - uses: ./.github/actions/target-checkout
      - id: biased-lang-linter
        uses: splunk/biased-lang-linter@main
        continue-on-error: false
