name: "Agreements"

permissions:
  contents: write
  pull-requests: write

on:
  issue_comment:
    types: [ created ]
  pull_request_target:
    types: [ opened, closed, synchronize ]

jobs:
  ContributorLicenseAgreement:
    runs-on: ubuntu-latest
    steps:
      - name: "CLA Assistant"
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request_target'
        uses: cla-assistant/github-action@v2.1.3-beta
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          path-to-signatures: "signatures/version1/cla.json"
          path-to-document: "https://github.com/splunk/cla-agreement/blob/main/CLA.md" # e.g. a CLA or a DCO document
          branch: "main"
          allowlist: dependabot[bot]
          remote-organization-name: splunk
          remote-repository-name: cla-agreement
  CodeOfConduct:
    runs-on: ubuntu-latest
    steps:
      - name: "COC Assistant"
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the Code of Conduct and I hereby accept the Terms') || github.event_name == 'pull_request_target'
        uses: cla-assistant/github-action@v2.1.3-beta
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          path-to-signatures: "signatures/version1/coc.json"
          path-to-document: "https://github.com/splunk/cla-agreement/blob/main/CODE_OF_CONDUCT.md" # e.g. a COC or a DCO document
          branch: "main"
          allowlist: dependabot[bot]
          remote-organization-name: splunk
          remote-repository-name: cla-agreement
          custom-pr-sign-comment: "I have read the Code of Conduct and I hereby accept the Terms"
          create-file-commit-message: "For example: Creating file for storing COC Signatures"
          signed-commit-message: "$contributorName has signed the COC in #$pullRequestNo"
          custom-notsigned-prcomment: "All contributors have NOT signed the COC Document"
          custom-allsigned-prcomment: "****CLA Assistant Lite bot**** All contributors have signed the COC  ✍️ ✅"